spring:
  application:
    name: api-gateway
server:
  port: 8080
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 15000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}   
